drop table item cascade constraints purge;
create table item(
	ITEM_ID			NUMBER(20),
	ITEM_NAME		VARCHAR2(30),
	ITEM_SELLER		VARCHAR2(20),
	ITEM_PRICE		NUMBER(10),
	ITEM_STOCK		NUMBER(10),
	ITEM_DISCOUNT	NUMBER(10),
	ITEM_CATEGORY	VARCHAR2(20),
	ITEM_TYPE		VARCHAR2(20),
	ITEM_LIKEBTN	NUMBER(10),
	ITEM_REGDATE	DATE DEFAULT SYSDATE,
	ITEM_FILE		VARCHAR2(100),
	ITEM_TIMESALE	VARCHAR2(20),
	ITEM_SEASON		NUMBER(2),
	ITEM_ADDRESS	VARCHAR2(10),
	ITEM_DESCRIPTION	VARCHAR2(100),
	PRIMARY KEY(ITEM_ID)
);

INSERT INTO ITEM 
(ITEM_ID, ITEM_NAME, ITEM_PRICE, ITEM_STOCK, ITEM_FILE, ITEM_DESCRIPTION) 
VALUES(1, '포도', 10000, 10, '', '맛있는 포도입니다.');

select * from ITEM;